### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by BPTPW** [epcdiy/timemachineplus#5]
以下是日志内容：
```
2023-07-27 14:31:18,359 耗时：0 [日志来自：serviceRun                               日志类型: INFO  日志内容：init db...]
2023-07-27 14:31:18,611 耗时：252 [日志来自：MySQLHelper                              日志类型: ERROR 日志内容：com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]
2023-07-27 14:31:18,668 耗时：309 [日志来自：serviceRun                               日志类型: INFO  日志内容：using rand seed :22255375459000]
2023-07-27 14:31:18,670 耗时：311 [日志来自：serviceRun                               日志类型: INFO  日志内容：loadBackupRoot]\
```
数据库位置以及登录信息已正确配置，数据表已创建
MySQL版本：8.0.33
JAVA版本：20.0.1

**Comment by BPTPW** [comment]
补充一段日志
![image](https://github.com/epcdiy/timemachineplus/assets/62642316/899e4bb4-faf8-43a6-819e-e26c9f99b351)

**Comment by BPTPW** [comment]
补充一段日志

```
2023-07-28 11:37:36,316 耗时：0 [日志来自：serviceRun                               日志类型: INFO  日志内容：init db...]
  Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
Fri Jul 28 11:37:36 CST 2023 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2023-07-28 11:37:36,595 耗时：279 [日志来自：MySQLHelper                              日志类型: ERROR 日志内容：com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]
  2023-07-28 11:37:36,655 耗时：339 [日志来自：serviceRun                               日志类型: INFO  日志内容：using rand seed :11683361005400]
  2023-07-28 11:37:36,655 耗时：339 [日志来自：serviceRun                               日志类型: INFO  日志内容：loadBackupRoot]
  java.lang.NullPointerException: Cannot invoke "java.sql.Connection.isValid(int)" because "this.conn" is null
        at MySQLHelper.querySql(MySQLHelper.java:206)
        at serviceRun.loadBackupRoot(serviceRun.java:50)
        at serviceRun.main(serviceRun.java:443)
```

![image](https://github.com/epcdiy/timemachineplus/assets/62642316/95253f2f-142a-40db-8080-0190192bbdb5)

**Comment by BPTPW** [comment]
通过降级MySQL解决了这个问题
但是又出现了拷贝错误的问题
```
2023-07-28 11:55:11,250 耗时：0 [日志来自：serviceRun                               日志类型: INFO  日志内容：init db...]
  Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
2023-07-28 11:55:11,436 耗时：186 [日志来自：MySQLHelper                              日志类型: INFO  日志内容：mysql connected!]
  2023-07-28 11:55:11,651 耗时：401 [日志来自：serviceRun                               日志类型: INFO  日志内容：using rand seed :12738356895700]
  2023-07-28 11:55:11,651 耗时：401 [日志来自：serviceRun                               日志类型: INFO  日志内容：loadBackupRoot]
  2023-07-28 11:55:11,685 耗时：435 [日志来自：serviceRun                               日志类型: INFO  日志内容：Loading File list:E:\www]
  2023-07-28 11:55:11,714 耗时：464 [日志来自：serviceRun                               日志类型: INFO  日志内容：Loading CurrentFile In Db:17]
  2023-07-28 11:55:11,716 耗时：466 [日志来自：serviceRun                               日志类型: INFO  日志内容：begin xcopy! total:7]
  2023-07-28 11:55:11,753 耗时：503 [日志来自：serviceRun                               日志类型: ERROR 日志内容：failed to copy file from E:\www\file\web.config to E:\TimemachineBackup\BACKUPDATABASE\319502885d2045791e98d25326cef95b_1690516511750]
  2023-07-28 11:55:11,753 耗时：503 [日志来自：serviceRun                               日志类型: ERROR 日志内容：拷贝错误！退出...]
```
文件名中是否含有中文都无法拷贝
